#!/bin/sh

case "$1" in
    start)
        echo "AESD Socket Starting..."
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "AESD Socket Stopping...."
        start-stop-daemon -K -n aesdsocket
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "AESD Socket Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
